name: build Multiple Environments
on:
  push:
    branches:
      - jobs-artifacts-outputs
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build Artifact
        run: echo "Build Complet" > result.txt
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-result
          path: result.txt
      - name: Set version output
        id: set_version_output
        run: echo "version=v1.0" >> $GITHUB_OUTPUT
    outputs:
      version: ${{ steps.set_version_output.outputs.version }}
  print-version:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Print Version
        run: echo "The version is ${{ needs.build.outputs.version}}"
